frontend-docker-push:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  needs: ["frontend-build"]
  before_script:
    - echo "$BACKEND_DOCKER_PASSWORD" | docker login -u "$BACKEND_DOCKER_USERNAME" --password-stdin
  script:
    - |
      echo "🚀 [Frontend] Starting Docker Build & Push..."
      cd $[[ inputs.project_dir ]]

      SAFE_TAG=$(echo $CI_COMMIT_REF_NAME | sed 's/\//_/g')
      IMAGE_NAME="$BACKEND_DOCKER_USERNAME/autowing-frontend:$SAFE_TAG"

      # 빌드 인자(--build-arg)를 통해 GitLab 변수를 Dockerfile 내부로 전달
      docker build \
        --build-arg VITE_WS_BASE_URL="$VITE_WS_BASE_URL" \
        --build-arg VITE_API_BASE_URL="$VITE_API_BASE_URL" \
        -t $IMAGE_NAME .

      docker push $IMAGE_NAME
      echo "🚀 Deployment Image [$IMAGE_NAME] Pushed Successfully!"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH =~ /^hotfix\/.*/'
      changes:
        - Frontend/**/*
