--
-- PostgreSQL database dump
--

\restrict c674bp78cH7DAA9sCdhKZcnWG6yxeclXPagiW9etD8kHKX89ATbIvGF038Y8BwY

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: aircraft; Type: TABLE; Schema: public; Owner: A402
--

CREATE TABLE public.aircraft (
    length double precision NOT NULL,
    width double precision NOT NULL,
    aircraft_id bigint NOT NULL,
    registration_num character varying(20) NOT NULL,
    type_code character varying(30) NOT NULL,
    description character varying(255)
);


ALTER TABLE public.aircraft OWNER TO "A402";

--
-- Name: aircraft_aircraft_id_seq; Type: SEQUENCE; Schema: public; Owner: A402
--

ALTER TABLE public.aircraft ALTER COLUMN aircraft_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aircraft_aircraft_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: driving_log; Type: TABLE; Schema: public; Owner: A402
--

CREATE TABLE public.driving_log (
    battery integer,
    heading double precision,
    posx double precision,
    posy double precision,
    velocity double precision,
    created_at timestamp(6) without time zone NOT NULL,
    log_id bigint NOT NULL,
    mission_id bigint,
    towing_car_id bigint NOT NULL,
    car_status character varying(20),
    mission_status character varying(20),
    CONSTRAINT driving_log_car_status_check CHECK (((car_status)::text = ANY ((ARRAY['IDLE'::character varying, 'MOVING_TO_GATE'::character varying, 'DOCKING'::character varying, 'TOWING'::character varying, 'UNDOCKING'::character varying, 'WAITING_FOR_RETURN'::character varying, 'RETURNING'::character varying, 'STOP'::character varying, 'ERROR'::character varying])::text[]))),
    CONSTRAINT driving_log_mission_status_check CHECK (((mission_status)::text = ANY ((ARRAY['RUNNING'::character varying, 'PAUSED'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.driving_log OWNER TO "A402";

--
-- Name: driving_log_seq; Type: SEQUENCE; Schema: public; Owner: A402
--

CREATE SEQUENCE public.driving_log_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.driving_log_seq OWNER TO "A402";

--
-- Name: edge; Type: TABLE; Schema: public; Owner: A402
--

CREATE TABLE public.edge (
    distance double precision NOT NULL,
    max_speed integer,
    travel_time double precision,
    dst_node_id bigint NOT NULL,
    edge_id bigint NOT NULL,
    src_node_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    edge_code character varying(30),
    restriction_info character varying(50),
    waypoints text,
    CONSTRAINT edge_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'BLOCKED'::character varying])::text[])))
);


ALTER TABLE public.edge OWNER TO "A402";

--
-- Name: edge_edge_id_seq; Type: SEQUENCE; Schema: public; Owner: A402
--

ALTER TABLE public.edge ALTER COLUMN edge_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.edge_edge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flight; Type: TABLE; Schema: public; Owner: A402
--

CREATE TABLE public.flight (
    departure_date date,
    aircraft_id bigint,
    assigned_towing_car_id bigint,
    flight_schedule_id bigint NOT NULL,
    pilot_id bigint,
    scheduled_time timestamp(6) without time zone,
    towing_car_id bigint,
    flight_number character varying(20),
    node_code character varying(30)
);


ALTER TABLE public.flight OWNER TO "A402";

--
-- Name: flight_flight_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: A402
--

ALTER TABLE public.flight ALTER COLUMN flight_schedule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flight_flight_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: map_info; Type: TABLE; Schema: public; Owner: A402
--

CREATE TABLE public.map_info (
    basic_map boolean,
    height integer NOT NULL,
    max_speed double precision,
    origin_x double precision,
    origin_y double precision,
    resolution double precision NOT NULL,
    width integer NOT NULL,
    map_id bigint NOT NULL,
    map_code character varying(30),
    image_path character varying(255)
);


ALTER TABLE public.map_info OWNER TO "A402";

--
-- Name: map_info_map_id_seq; Type: SEQUENCE; Schema: public; Owner: A402
--

ALTER TABLE public.map_info ALTER COLUMN map_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.map_info_map_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mission; Type: TABLE; Schema: public; Owner: A402
--

CREATE TABLE public.mission (
    assigned_at timestamp(6) without time zone,
    completed_at timestamp(6) without time zone,
    flight_schedule_id bigint,
    mission_id bigint NOT NULL,
    pilot_id bigint,
    started_at timestamp(6) without time zone,
    towing_car_id bigint,
    status character varying(20),
    depart_node character varying(30),
    dest_node character varying(30),
    route_edge_ids text,
    CONSTRAINT mission_status_check CHECK (((status)::text = ANY ((ARRAY['RUNNING'::character varying, 'PAUSED'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.mission OWNER TO "A402";

--
-- Name: mission_log; Type: TABLE; Schema: public; Owner: A402
--

CREATE TABLE public.mission_log (
    car_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    log_id bigint NOT NULL,
    mission_id bigint,
    type character varying(20) NOT NULL,
    message character varying(255) NOT NULL,
    CONSTRAINT mission_log_type_check CHECK (((type)::text = ANY ((ARRAY['COMMAND'::character varying, 'ALERT'::character varying, 'REQUEST'::character varying, 'CONTROL'::character varying, 'DISPATCH'::character varying, 'APPROVE'::character varying, 'REJECT'::character varying])::text[])))
);


ALTER TABLE public.mission_log OWNER TO "A402";

--
-- Name: mission_log_log_id_seq; Type: SEQUENCE; Schema: public; Owner: A402
--

ALTER TABLE public.mission_log ALTER COLUMN log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mission_log_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mission_mission_id_seq; Type: SEQUENCE; Schema: public; Owner: A402
--

ALTER TABLE public.mission ALTER COLUMN mission_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mission_mission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: node; Type: TABLE; Schema: public; Owner: A402
--

CREATE TABLE public.node (
    pos_x double precision NOT NULL,
    pos_y double precision NOT NULL,
    node_id bigint NOT NULL,
    node_type character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    node_code character varying(30),
    restriction_info character varying(50),
    CONSTRAINT node_node_type_check CHECK (((node_type)::text = ANY ((ARRAY['NODE'::character varying, 'GATE'::character varying, 'RUNWAY'::character varying, 'PARKING_LOT'::character varying])::text[]))),
    CONSTRAINT node_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'BLOCKED'::character varying])::text[])))
);


ALTER TABLE public.node OWNER TO "A402";

--
-- Name: node_node_id_seq; Type: SEQUENCE; Schema: public; Owner: A402
--

ALTER TABLE public.node ALTER COLUMN node_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.node_node_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: towing_car; Type: TABLE; Schema: public; Owner: A402
--

CREATE TABLE public.towing_car (
    battery integer NOT NULL,
    last_heading double precision,
    last_pos_x double precision,
    last_pos_y double precision,
    last_velocity double precision,
    current_mission_id bigint,
    last_node_id bigint,
    towing_car_id bigint NOT NULL,
    car_status character varying(20) NOT NULL,
    code character varying(20) NOT NULL,
    CONSTRAINT towing_car_car_status_check CHECK (((car_status)::text = ANY ((ARRAY['IDLE'::character varying, 'MOVING_TO_GATE'::character varying, 'DOCKING'::character varying, 'TOWING'::character varying, 'UNDOCKING'::character varying, 'WAITING_FOR_RETURN'::character varying, 'RETURNING'::character varying, 'STOP'::character varying, 'ERROR'::character varying])::text[])))
);


ALTER TABLE public.towing_car OWNER TO "A402";

--
-- Name: towing_car_towing_car_id_seq; Type: SEQUENCE; Schema: public; Owner: A402
--

ALTER TABLE public.towing_car ALTER COLUMN towing_car_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.towing_car_towing_car_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: A402
--

CREATE TABLE public.users (
    created_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    employee_code character varying(20) NOT NULL,
    role character varying(20) NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['PILOT'::character varying, 'ATC'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO "A402";

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: A402
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: aircraft; Type: TABLE DATA; Schema: public; Owner: A402
--

COPY public.aircraft (length, width, aircraft_id, registration_num, type_code, description) FROM stdin;
39	35	1	HL7777	B737	\N
\.


--
-- Data for Name: driving_log; Type: TABLE DATA; Schema: public; Owner: A402
--

COPY public.driving_log (battery, heading, posx, posy, velocity, created_at, log_id, mission_id, towing_car_id, car_status, mission_status) FROM stdin;
85	0	0	0	0	2026-02-09 01:59:50.88119	1	\N	1	IDLE	RUNNING
85	0	0	0	0	2026-02-09 01:59:51.878254	2	\N	1	IDLE	RUNNING
85	0	0	0	0	2026-02-09 01:59:52.87764	3	\N	1	IDLE	RUNNING
85	0	0	0	0	2026-02-09 01:59:53.877489	4	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 01:59:54.876785	5	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 01:59:55.876177	6	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 01:59:56.876938	7	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 01:59:57.877051	8	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 01:59:58.876349	9	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 01:59:59.876549	10	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:00.876767	11	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:01.877555	12	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:02.876989	13	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:03.876857	14	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:04.877264	15	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:05.877134	16	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:06.877269	17	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:07.876603	18	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:08.877202	19	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:09.876868	20	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:10.876839	21	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:11.880333	22	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:12.881296	23	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:13.880948	24	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:14.880242	25	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:15.879792	26	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:16.879618	27	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:17.880467	28	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:18.879635	29	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:19.880841	30	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:20.879809	31	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:21.879049	32	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:22.879199	33	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:23.879758	34	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:24.879381	35	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:25.88001	36	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:26.879792	37	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:27.880384	38	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:28.880598	39	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:29.879334	40	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:30.886298	41	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:31.879575	42	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:32.87976	43	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:33.880523	44	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:34.8845	45	\N	1	IDLE	RUNNING
85	-1.57	-0.93	2.31	0	2026-02-09 02:00:35.879617	46	\N	1	IDLE	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:36.882666	47	\N	1	IDLE	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:37.883151	48	\N	1	IDLE	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:38.878808	49	\N	1	IDLE	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:39.880877	50	\N	1	IDLE	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:40.880317	51	\N	1	IDLE	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:41.882032	52	\N	1	IDLE	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:42.211393	53	\N	1	MOVING_TO_GATE	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:42.875547	54	\N	1	MOVING_TO_GATE	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:43.879308	55	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	-0.07	2026-02-09 02:00:44.876217	56	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	-0.07	2026-02-09 02:00:45.88004	57	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	-0.07	2026-02-09 02:00:46.878347	58	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	-0.07	2026-02-09 02:00:47.87538	59	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	-0.07	2026-02-09 02:00:48.878977	60	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:49.877544	61	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:50.878921	62	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:51.879287	63	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:52.876816	64	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:53.878999	65	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:54.877175	66	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:55.879039	67	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:56.880025	68	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:57.87869	69	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:58.879227	70	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:00:59.879021	71	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:01:00.878714	72	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:01:01.876067	73	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:01:02.878988	74	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:01:03.879168	75	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:01:04.879729	76	\N	1	DOCKING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:01:05.694718	77	\N	1	TOWING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:01:05.891257	78	\N	1	TOWING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:01:06.878257	79	\N	1	TOWING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:01:07.88108	80	\N	1	TOWING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:01:08.879058	81	\N	1	TOWING	RUNNING
85	-1.57	-0.92	2.31	0	2026-02-09 02:01:09.879201	82	\N	1	TOWING	RUNNING
85	-1.51	-0.93	2.39	0	2026-02-09 02:01:10.880347	83	\N	1	TOWING	RUNNING
85	-1.51	-0.93	2.39	0	2026-02-09 02:01:11.882273	84	\N	1	TOWING	RUNNING
85	-1.51	-0.93	2.39	0	2026-02-09 02:01:12.882291	85	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:13.877345	86	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:14.879095	87	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:15.876299	88	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:16.878596	89	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:17.877769	90	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:18.876409	91	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:19.877415	92	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:20.87898	93	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:21.878879	94	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:22.877415	95	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:23.879504	96	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:24.880025	97	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:25.885489	98	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:26.880641	99	\N	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0	2026-02-09 02:01:27.0169	100	1	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0.3013052145458152	2026-02-09 02:01:27.88167	101	1	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0.2898243993456052	2026-02-09 02:01:28.88005	102	1	1	TOWING	RUNNING
85	-1.57	-0.94	2.4	0.27997859312405426	2026-02-09 02:01:29.881131	103	1	1	TOWING	RUNNING
85	-1.46	-0.95	2.16	0.2545663203251879	2026-02-09 02:01:30.877322	104	1	1	TOWING	RUNNING
85	-1.46	-0.95	2.16	0.2606410865130755	2026-02-09 02:01:31.876922	105	1	1	TOWING	RUNNING
85	-1.46	-0.95	2.16	0.263963844002791	2026-02-09 02:01:32.877393	106	1	1	TOWING	RUNNING
85	-1.35	-0.91	1.89	0.2568594075107491	2026-02-09 02:01:33.880577	107	1	1	TOWING	RUNNING
85	-1.35	-0.91	1.89	0.26930196418478564	2026-02-09 02:01:34.880395	108	1	1	TOWING	RUNNING
85	-1.35	-0.91	1.89	0.28275985967327105	2026-02-09 02:01:35.880235	109	1	1	TOWING	RUNNING
85	-1.26	-0.84	1.61	0.27864105793985067	2026-02-09 02:01:36.877722	110	1	1	TOWING	RUNNING
85	-1.26	-0.84	1.61	0.30452647296606145	2026-02-09 02:01:37.877062	111	1	1	TOWING	RUNNING
85	-1.26	-0.84	1.61	0.35677027358725266	2026-02-09 02:01:38.879765	112	1	1	TOWING	RUNNING
85	-1.1	-0.69	1.29	0.49207553285503697	2026-02-09 02:01:39.879767	113	1	1	TOWING	RUNNING
85	-1.1	-0.69	1.29	0.5	2026-02-09 02:01:40.877712	114	1	1	TOWING	RUNNING
85	-1	-0.51	1	0.5	2026-02-09 02:01:41.878035	115	1	1	TOWING	RUNNING
85	-1	-0.51	1	0.5	2026-02-09 02:01:42.876818	116	1	1	TOWING	RUNNING
85	-1	-0.34	0.73	0.47549914004955285	2026-02-09 02:01:43.877193	117	1	1	TOWING	RUNNING
85	-1	-0.34	0.73	0.36911069145437914	2026-02-09 02:01:44.876653	118	1	1	TOWING	RUNNING
85	-1.1	-0.15	0.44	0.323842455482498	2026-02-09 02:01:45.877123	119	1	1	TOWING	RUNNING
85	-1.1	-0.15	0.44	0.33941095198425286	2026-02-09 02:01:46.878065	120	1	1	TOWING	RUNNING
85	-1.27	-0.05	0.16	0.34921893954202854	2026-02-09 02:01:47.879829	121	1	1	TOWING	RUNNING
85	-1.27	-0.05	0.16	0.4042265359806799	2026-02-09 02:01:48.877896	122	1	1	TOWING	RUNNING
85	-1.45	-0.01	-0.12	0.4091166527215837	2026-02-09 02:01:49.877265	123	1	1	TOWING	RUNNING
85	-1.57	0	-0.4	0.30800584376301887	2026-02-09 02:01:50.876694	124	1	1	TOWING	RUNNING
85	-1.57	0	-0.4	0	2026-02-09 02:01:51.892402	125	1	1	UNDOCKING	RUNNING
85	-1.57	0	-0.4	0	2026-02-09 02:01:52.881244	126	1	1	UNDOCKING	RUNNING
85	-1.57	0	-0.4	0	2026-02-09 02:01:53.882133	127	1	1	UNDOCKING	RUNNING
85	-1.57	0	-0.4	0	2026-02-09 02:01:54.883724	128	1	1	UNDOCKING	RUNNING
85	-1.57	0	-0.4	0	2026-02-09 02:01:55.881255	129	1	1	UNDOCKING	RUNNING
85	-1.57	0	-0.4	0	2026-02-09 02:01:55.927502	130	1	1	RETURNING	RUNNING
85	-1.57	0	-0.4	0	2026-02-09 02:01:56.013815	131	1	1	RETURNING	RUNNING
85	-1.57	0	-0.4	1.916	2026-02-09 02:01:56.895283	132	1	1	RETURNING	RUNNING
85	-1.65	-0.02	-0.69	1.82	2026-02-09 02:01:57.879157	133	1	1	RETURNING	RUNNING
85	-1.69	-0.05	-0.95	1.726	2026-02-09 02:01:58.878503	134	1	1	RETURNING	RUNNING
85	-1.71	-0.08	-1.21	1.6320000000000001	2026-02-09 02:01:59.879111	135	1	1	RETURNING	RUNNING
85	-1.73	-0.11	-1.46	1.538	2026-02-09 02:02:00.881868	136	1	1	RETURNING	RUNNING
85	-1.75	-0.15	-1.72	1.332	2026-02-09 02:02:01.883283	137	1	1	RETURNING	RUNNING
85	-1.86	-0.23	-1.96	1.044	2026-02-09 02:02:02.878711	138	1	1	RETURNING	RUNNING
85	-1.86	-0.23	-1.96	0.762	2026-02-09 02:02:03.878108	139	1	1	RETURNING	RUNNING
85	-2	-0.33	-2.21	0.4799999999999999	2026-02-09 02:02:04.880371	140	1	1	RETURNING	RUNNING
85	-2.1	-0.44	-2.44	0.198	2026-02-09 02:02:05.877309	141	1	1	RETURNING	RUNNING
85	-2.1	-0.44	-2.44	0	2026-02-09 02:02:06.880051	142	1	1	RETURNING	RUNNING
85	-2.1	-0.44	-2.44	-1.8479999999999999	2026-02-09 02:02:07.881972	143	1	1	RETURNING	RUNNING
85	-2.59	-0.35	-2.33	-1.66	2026-02-09 02:02:08.87939	144	1	1	RETURNING	RUNNING
85	-2.82	-0.2	-2.23	-1.485	2026-02-09 02:02:09.881097	145	1	1	RETURNING	RUNNING
85	-3.09	0.06	-2.16	-1.3675000000000002	2026-02-09 02:02:10.877645	146	1	1	RETURNING	RUNNING
85	-3.12	0.32	-2.17	-1.2475	2026-02-09 02:02:11.880233	147	1	1	RETURNING	RUNNING
85	-3.11	0.61	-2.17	-1.13	2026-02-09 02:02:12.880507	148	1	1	RETURNING	RUNNING
85	-3.11	0.85	-2.19	-1.01	2026-02-09 02:02:13.877332	149	1	1	RETURNING	RUNNING
85	-3.11	1.13	-2.16	1.1674285714285715	2026-02-09 02:02:14.879031	150	1	1	RETURNING	RUNNING
85	-3.11	1.13	-2.16	1.0868571428571427	2026-02-09 02:02:15.880683	151	1	1	RETURNING	RUNNING
85	-3.11	1.13	-2.16	1.0062857142857142	2026-02-09 02:02:16.878279	152	1	1	RETURNING	RUNNING
85	2.87	0.9	-2.09	0.9257142857142857	2026-02-09 02:02:17.879375	153	1	1	RETURNING	RUNNING
85	2.76	0.67	-1.98	0.8434285714285714	2026-02-09 02:02:18.877996	154	1	1	RETURNING	RUNNING
85	2.58	0.44	-1.83	0.7628571428571428	2026-02-09 02:02:19.882518	155	1	1	RETURNING	RUNNING
85	2.58	0.44	-1.83	0.6822857142857142	2026-02-09 02:02:20.880844	156	1	1	RETURNING	RUNNING
85	2.43	0.21	-1.65	0.6017142857142858	2026-02-09 02:02:21.878533	157	1	1	RETURNING	RUNNING
85	2.28	-0	-1.42	0.5211428571428571	2026-02-09 02:02:22.878315	158	1	1	RETURNING	RUNNING
85	2.28	-0	-1.42	0.4405714285714285	2026-02-09 02:02:23.881813	159	1	1	RETURNING	RUNNING
85	2.11	-0.2	-1.12	0.3582857142857143	2026-02-09 02:02:24.879624	160	1	1	RETURNING	RUNNING
85	1.96	-0.33	-0.85	0.2777142857142857	2026-02-09 02:02:25.87948	161	1	1	RETURNING	RUNNING
85	1.96	-0.33	-0.85	0.19542857142857137	2026-02-09 02:02:26.878912	162	1	1	RETURNING	RUNNING
85	1.96	-0.33	-0.85	0.1148571428571429	2026-02-09 02:02:27.880576	163	1	1	RETURNING	RUNNING
85	1.78	-0.4	-0.59	0.034285714285714294	2026-02-09 02:02:28.881411	164	1	1	RETURNING	RUNNING
85	1.78	-0.4	-0.59	1.97	2026-02-09 02:02:29.87959	165	1	1	RETURNING	RUNNING
85	1.78	-0.4	-0.59	1.49	2026-02-09 02:02:30.877412	166	1	1	RETURNING	RUNNING
85	1.68	-0.44	-0.32	1.02	2026-02-09 02:02:31.879141	167	1	1	RETURNING	RUNNING
85	1.61	-0.46	-0.07	0.54	2026-02-09 02:02:32.88134	168	1	1	RETURNING	RUNNING
85	1.61	-0.46	-0.07	0.07000000000000006	2026-02-09 02:02:33.877943	169	1	1	RETURNING	RUNNING
85	1.54	-0.45	0.18	0	2026-02-09 02:02:34.903762	170	1	1	IDLE	RUNNING
85	1.54	-0.45	0.18	0	2026-02-09 02:02:35.881825	171	1	1	IDLE	RUNNING
85	1.54	-0.45	0.18	0	2026-02-09 02:02:36.883132	172	1	1	IDLE	RUNNING
85	1.54	-0.45	0.18	0	2026-02-09 02:02:37.884596	173	1	1	IDLE	RUNNING
85	1.54	-0.45	0.18	0	2026-02-09 02:02:38.880779	174	1	1	IDLE	RUNNING
85	1.54	-0.45	0.18	0	2026-02-09 02:02:39.879808	175	1	1	IDLE	RUNNING
85	1.54	-0.45	0.18	0	2026-02-09 02:02:40.88175	176	1	1	IDLE	RUNNING
85	1.54	-0.45	0.18	0	2026-02-09 02:02:41.881869	177	1	1	IDLE	RUNNING
85	1.54	-0.45	0.18	0.35	2026-02-09 02:02:42.881365	178	1	1	IDLE	RUNNING
85	1.54	-0.45	0.18	0	2026-02-09 02:02:43.881749	179	1	1	IDLE	RUNNING
85	1.46	-0.41	0.44	0.35	2026-02-09 02:02:44.88021	180	1	1	IDLE	RUNNING
85	1.46	-0.41	0.44	0	2026-02-09 02:02:45.881107	181	1	1	IDLE	RUNNING
85	1.56	-0.62	0.2	0	2026-02-09 02:02:46.880317	182	1	1	IDLE	RUNNING
85	1.35	-0.91	-0.06	0	2026-02-09 02:02:47.892448	183	1	1	IDLE	RUNNING
85	1.35	-0.91	-0.06	0	2026-02-09 02:02:48.880002	184	1	1	IDLE	RUNNING
85	1.35	-0.91	-0.06	0.35	2026-02-09 02:02:49.882638	185	1	1	IDLE	RUNNING
85	1.35	-0.91	-0.06	0	2026-02-09 02:02:50.881163	186	1	1	IDLE	RUNNING
85	1.42	-1.06	0.21	0.35	2026-02-09 02:02:51.88017	187	1	1	IDLE	RUNNING
85	1.42	-1.06	0.21	0	2026-02-09 02:02:52.883389	188	1	1	IDLE	RUNNING
85	1.39	-1.05	0.41	0.35	2026-02-09 02:02:53.880575	189	1	1	IDLE	RUNNING
85	1.39	-1.05	0.41	0.35	2026-02-09 02:02:54.87997	190	1	1	IDLE	RUNNING
85	1.33	-1	0.61	0.35	2026-02-09 02:02:55.880061	191	1	1	IDLE	RUNNING
85	1.27	-0.94	0.84	0	2026-02-09 02:02:56.881701	192	1	1	IDLE	RUNNING
85	1.27	-0.94	0.84	0.35	2026-02-09 02:02:57.88373	193	1	1	IDLE	RUNNING
85	1.14	-0.84	1.06	0.35	2026-02-09 02:02:58.880898	194	1	1	IDLE	RUNNING
85	1.14	-0.84	1.06	0	2026-02-09 02:02:59.881138	195	1	1	IDLE	RUNNING
85	1.21	-0.76	1.28	0	2026-02-09 02:03:00.880078	196	1	1	IDLE	RUNNING
85	1.21	-0.76	1.28	0	2026-02-09 02:03:01.880487	197	1	1	IDLE	RUNNING
85	1.21	-0.76	1.28	0	2026-02-09 02:03:02.881234	198	1	1	IDLE	RUNNING
85	1.21	-0.76	1.28	0	2026-02-09 02:03:03.880208	199	1	1	IDLE	RUNNING
85	1.21	-0.76	1.28	0	2026-02-09 02:03:04.880937	200	1	1	IDLE	RUNNING
85	1.21	-0.76	1.28	0	2026-02-09 02:03:05.882053	201	1	1	IDLE	RUNNING
85	1.21	-0.76	1.28	0	2026-02-09 02:03:06.88069	202	1	1	IDLE	RUNNING
85	1.49	-0.73	1.22	0	2026-02-09 02:03:07.881338	203	1	1	IDLE	RUNNING
85	1.49	-0.73	1.22	0	2026-02-09 02:03:08.880188	204	1	1	IDLE	RUNNING
85	1.73	-0.67	1.08	0	2026-02-09 02:03:09.880622	205	1	1	IDLE	RUNNING
85	1.73	-0.67	1.08	0	2026-02-09 02:03:10.881622	206	1	1	IDLE	RUNNING
85	1.73	-0.67	1.08	0	2026-02-09 02:03:11.879964	207	1	1	IDLE	RUNNING
85	1.73	-0.67	1.08	0	2026-02-09 02:03:12.88017	208	1	1	IDLE	RUNNING
85	1.73	-0.67	1.08	0	2026-02-09 02:03:13.880578	209	1	1	IDLE	RUNNING
85	1.73	-0.67	1.08	0	2026-02-09 02:03:14.881079	210	1	1	IDLE	RUNNING
85	1.73	-0.67	1.08	0	2026-02-09 02:03:15.87945	211	1	1	IDLE	RUNNING
85	1.5	-0.68	0.89	0	2026-02-09 02:03:16.880662	212	1	1	IDLE	RUNNING
85	1.5	-0.68	0.89	0	2026-02-09 02:03:17.880689	213	1	1	IDLE	RUNNING
85	1.5	-0.68	0.89	0	2026-02-09 02:03:18.880788	214	1	1	IDLE	RUNNING
85	1.5	-0.68	0.89	0	2026-02-09 02:03:19.880228	215	1	1	IDLE	RUNNING
85	1.5	-0.68	0.89	0	2026-02-09 02:03:20.88119	216	1	1	IDLE	RUNNING
85	1.5	-0.68	0.89	0	2026-02-09 02:03:21.880177	217	1	1	IDLE	RUNNING
85	1.5	-0.68	0.89	0	2026-02-09 02:03:22.882675	218	1	1	IDLE	RUNNING
85	1.5	-0.68	0.89	0	2026-02-09 02:03:23.880569	219	1	1	IDLE	RUNNING
85	1.5	-0.68	0.89	0	2026-02-09 02:03:24.880125	220	1	1	IDLE	RUNNING
85	1.5	-0.68	0.89	0	2026-02-09 02:03:25.881217	221	1	1	IDLE	RUNNING
85	1.5	-0.68	0.89	0	2026-02-09 02:03:26.881594	222	1	1	IDLE	RUNNING
85	1.5	-0.68	0.89	0.35	2026-02-09 02:03:27.879986	223	1	1	IDLE	RUNNING
85	1.5	-0.68	0.89	0	2026-02-09 02:03:28.880725	224	1	1	IDLE	RUNNING
85	1.5	-0.68	0.89	0.35	2026-02-09 02:03:29.881292	225	1	1	IDLE	RUNNING
85	1.43	-0.62	1.14	0.35	2026-02-09 02:03:30.879786	226	1	1	IDLE	RUNNING
85	1.45	-0.59	1.36	0.35	2026-02-09 02:03:31.881953	227	1	1	IDLE	RUNNING
85	1.52	-0.56	1.58	0	2026-02-09 02:03:32.881578	228	1	1	IDLE	RUNNING
85	1.52	-0.56	1.58	0	2026-02-09 02:03:33.880564	229	1	1	IDLE	RUNNING
85	1.52	-0.56	1.58	0.35	2026-02-09 02:03:34.881614	230	1	1	IDLE	RUNNING
85	1.58	-0.55	1.83	0.35	2026-02-09 02:03:35.881026	231	1	1	IDLE	RUNNING
85	1.63	-0.57	2.09	0.35	2026-02-09 02:03:36.880132	232	1	1	IDLE	RUNNING
85	1.63	-0.57	2.09	0	2026-02-09 02:03:37.880989	233	1	1	IDLE	RUNNING
85	1.63	-0.57	2.09	0	2026-02-09 02:03:38.880807	234	1	1	IDLE	RUNNING
85	1.63	-0.57	2.09	0	2026-02-09 02:03:39.880425	235	1	1	IDLE	RUNNING
85	1.63	-0.57	2.09	0	2026-02-09 02:03:40.880959	236	1	1	IDLE	RUNNING
85	1.63	-0.57	2.09	0	2026-02-09 02:03:41.880692	237	1	1	IDLE	RUNNING
85	1.63	-0.57	2.09	0.35	2026-02-09 02:03:42.879972	238	1	1	IDLE	RUNNING
85	1.93	-0.58	2.23	0	2026-02-09 02:03:43.881089	239	1	1	IDLE	RUNNING
85	2.27	-0.5	2.19	0	2026-02-09 02:03:44.881702	240	1	1	IDLE	RUNNING
85	1.69	-0.62	2.04	0	2026-02-09 02:03:45.880302	241	1	1	IDLE	RUNNING
85	1.38	-0.52	2.06	0	2026-02-09 02:03:46.881523	242	1	1	IDLE	RUNNING
85	1.08	-0.37	2.11	0	2026-02-09 02:03:47.88141	243	1	1	IDLE	RUNNING
85	1.08	-0.37	2.11	0	2026-02-09 02:03:48.882224	244	1	1	IDLE	RUNNING
\.


--
-- Data for Name: edge; Type: TABLE DATA; Schema: public; Owner: A402
--

COPY public.edge (distance, max_speed, travel_time, dst_node_id, edge_id, src_node_id, status, edge_code, restriction_info, waypoints) FROM stdin;
0.10000000000000009	3	0.03333333333333336	2	1	1	AVAILABLE	E_n1_to_n2	NONE	[{"x":-0.895,"y":2.495},{"x":-0.895,"y":2.595}]
0.10000000000000009	3	0.03333333333333336	1	2	2	AVAILABLE	E_n2_to_n1	NONE	[{"x":-0.895,"y":2.595},{"x":-0.895,"y":2.495}]
2.224286090498023	3	0.7414286968326743	3	3	2	AVAILABLE	E_n2_to_n3	NONE	[{"x":-0.895,"y":2.595},{"x":-0.195,"y":0.495}]
2.224286090498023	3	0.7414286968326743	2	4	3	AVAILABLE	E_n3_to_n2	NONE	[{"x":-0.195,"y":0.495},{"x":-0.895,"y":2.595}]
1.507657214068412	3	0.5025524046894706	4	5	3	AVAILABLE	E_n3_to_n4	NONE	[{"x":-0.195,"y":0.495},{"x":-0.045,"y":-1.005}]
1.507657214068412	3	0.5025524046894706	3	6	4	AVAILABLE	E_n4_to_n3	NONE	[{"x":-0.045,"y":-1.005},{"x":-0.195,"y":0.495}]
1.6728899778359991	3	0.5576299926119997	5	7	4	AVAILABLE	E_n4_to_n5	NONE	[{"x":-0.045,"y":-1.005},{"x":-0.495,"y":-2.605}]
1.6728899778359991	3	0.5576299926119997	4	8	5	AVAILABLE	E_n5_to_n4	NONE	[{"x":-0.495,"y":-2.605},{"x":-0.045,"y":-1.005}]
1.9205017790968624	3	0.6401672596989542	6	9	5	AVAILABLE	E_n5_to_n6	NONE	[{"x":-0.495,"y":-2.605},{"x":-0.065,"y":-2.2419},{"x":1.205,"y":-1.805}]
1.9205017790968624	3	0.6401672596989542	5	10	6	AVAILABLE	E_n6_to_n5	NONE	[{"x":1.205,"y":-1.805},{"x":-0.065,"y":-2.2419},{"x":-0.495,"y":-2.605}]
2.6736881599626314	3	0.8912293866542105	7	11	6	AVAILABLE	E_n6_to_n7	NONE	[{"x":1.205,"y":-1.805},{"x":-0.2234,"y":-1.8101},{"x":-0.6311,"y":-1.5193},{"x":-0.895,"y":-1.005}]
2.6736881599626314	3	0.8912293866542105	6	12	7	AVAILABLE	E_n7_to_n6	NONE	[{"x":-0.895,"y":-1.005},{"x":-0.6311,"y":-1.5193},{"x":-0.2234,"y":-1.8101},{"x":1.205,"y":-1.805}]
1.4999999999999996	3	0.49999999999999983	8	13	7	AVAILABLE	E_n7_to_n8	NONE	[{"x":-0.895,"y":-1.005},{"x":-0.895,"y":0.495}]
1.4999999999999996	3	0.49999999999999983	7	14	8	AVAILABLE	E_n8_to_n7	NONE	[{"x":-0.895,"y":0.495},{"x":-0.895,"y":-1.005}]
\.


--
-- Data for Name: flight; Type: TABLE DATA; Schema: public; Owner: A402
--

COPY public.flight (departure_date, aircraft_id, assigned_towing_car_id, flight_schedule_id, pilot_id, scheduled_time, towing_car_id, flight_number, node_code) FROM stdin;
2026-02-09	1	1	1	1	2026-02-09 03:49:10.254603	1	KE001	n2
\.


--
-- Data for Name: map_info; Type: TABLE DATA; Schema: public; Owner: A402
--

COPY public.map_info (basic_map, height, max_speed, origin_x, origin_y, resolution, width, map_id, map_code, image_path) FROM stdin;
t	1500	10	-5.42	-3.68	0.05	2000	1	TEST_MAP_01	my_map.pgm
\.


--
-- Data for Name: mission; Type: TABLE DATA; Schema: public; Owner: A402
--

COPY public.mission (assigned_at, completed_at, flight_schedule_id, mission_id, pilot_id, started_at, towing_car_id, status, depart_node, dest_node, route_edge_ids) FROM stdin;
2026-02-09 02:01:26.967033	\N	1	1	1	\N	1	RUNNING	n2	n4	["E_n2_to_n3","E_n3_to_n4"]
\.


--
-- Data for Name: mission_log; Type: TABLE DATA; Schema: public; Owner: A402
--

COPY public.mission_log (car_id, created_at, log_id, mission_id, type, message) FROM stdin;
\N	2026-02-09 02:01:26.970879	1	1	APPROVE	Approved by atc@atc.com
\.


--
-- Data for Name: node; Type: TABLE DATA; Schema: public; Owner: A402
--

COPY public.node (pos_x, pos_y, node_id, node_type, status, node_code, restriction_info) FROM stdin;
-0.8893	2.5	1	PARKING_LOT	AVAILABLE	n1	NONE
-0.895	2.595	2	GATE	AVAILABLE	n2	NONE
-0.2	0.5	3	NODE	AVAILABLE	n3	NONE
-0.0307	-1	4	RUNWAY	AVAILABLE	n4	NONE
-0.48518	-2.6	5	NODE	AVAILABLE	n5	NONE
1.20518	-1.8	6	NODE	AVAILABLE	n6	NONE
-0.8893	-1	7	NODE	AVAILABLE	n7	NONE
-0.8893	0.5	8	PARKING_LOT	AVAILABLE	n8	NONE
\.


--
-- Data for Name: towing_car; Type: TABLE DATA; Schema: public; Owner: A402
--

COPY public.towing_car (battery, last_heading, last_pos_x, last_pos_y, last_velocity, current_mission_id, last_node_id, towing_car_id, car_status, code) FROM stdin;
85	1.08	-0.37	2.11	0	1	1	1	IDLE	TC01
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: A402
--

COPY public.users (created_at, user_id, employee_code, role, username, email, password) FROM stdin;
2026-02-09 01:49:09.819764	1	P001	PILOT	Maverick	pilot@atc.com	$2a$10$g7pvZG1zkGHWolsVd1vofeGLXGuFxQHX10Fxfhr2so.0OWNiuGw1O
2026-02-09 01:49:09.944894	2	A001	ATC	TowerControl	atc@atc.com	$2a$10$CBVDNsMKhFy1WYYiNwaAdeDA9UK3/.qAuN6gyZtx3lGcnbfLAviCi
\.


--
-- Name: aircraft_aircraft_id_seq; Type: SEQUENCE SET; Schema: public; Owner: A402
--

SELECT pg_catalog.setval('public.aircraft_aircraft_id_seq', 1, true);


--
-- Name: driving_log_seq; Type: SEQUENCE SET; Schema: public; Owner: A402
--

SELECT pg_catalog.setval('public.driving_log_seq', 244, true);


--
-- Name: edge_edge_id_seq; Type: SEQUENCE SET; Schema: public; Owner: A402
--

SELECT pg_catalog.setval('public.edge_edge_id_seq', 14, true);


--
-- Name: flight_flight_schedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: A402
--

SELECT pg_catalog.setval('public.flight_flight_schedule_id_seq', 1, true);


--
-- Name: map_info_map_id_seq; Type: SEQUENCE SET; Schema: public; Owner: A402
--

SELECT pg_catalog.setval('public.map_info_map_id_seq', 1, true);


--
-- Name: mission_log_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: A402
--

SELECT pg_catalog.setval('public.mission_log_log_id_seq', 1, true);


--
-- Name: mission_mission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: A402
--

SELECT pg_catalog.setval('public.mission_mission_id_seq', 1, true);


--
-- Name: node_node_id_seq; Type: SEQUENCE SET; Schema: public; Owner: A402
--

SELECT pg_catalog.setval('public.node_node_id_seq', 8, true);


--
-- Name: towing_car_towing_car_id_seq; Type: SEQUENCE SET; Schema: public; Owner: A402
--

SELECT pg_catalog.setval('public.towing_car_towing_car_id_seq', 1, true);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: A402
--

SELECT pg_catalog.setval('public.users_user_id_seq', 2, true);


--
-- Name: aircraft aircraft_pkey; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.aircraft
    ADD CONSTRAINT aircraft_pkey PRIMARY KEY (aircraft_id);


--
-- Name: aircraft aircraft_registration_num_key; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.aircraft
    ADD CONSTRAINT aircraft_registration_num_key UNIQUE (registration_num);


--
-- Name: driving_log driving_log_pkey; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.driving_log
    ADD CONSTRAINT driving_log_pkey PRIMARY KEY (created_at, log_id);


--
-- Name: edge edge_edge_code_key; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.edge
    ADD CONSTRAINT edge_edge_code_key UNIQUE (edge_code);


--
-- Name: edge edge_pkey; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.edge
    ADD CONSTRAINT edge_pkey PRIMARY KEY (edge_id);


--
-- Name: flight flight_assigned_towing_car_id_key; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.flight
    ADD CONSTRAINT flight_assigned_towing_car_id_key UNIQUE (assigned_towing_car_id);


--
-- Name: flight flight_flight_number_key; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.flight
    ADD CONSTRAINT flight_flight_number_key UNIQUE (flight_number);


--
-- Name: flight flight_pkey; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.flight
    ADD CONSTRAINT flight_pkey PRIMARY KEY (flight_schedule_id);


--
-- Name: map_info map_info_map_code_key; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.map_info
    ADD CONSTRAINT map_info_map_code_key UNIQUE (map_code);


--
-- Name: map_info map_info_pkey; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.map_info
    ADD CONSTRAINT map_info_pkey PRIMARY KEY (map_id);


--
-- Name: mission_log mission_log_pkey; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.mission_log
    ADD CONSTRAINT mission_log_pkey PRIMARY KEY (log_id);


--
-- Name: mission mission_pkey; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.mission
    ADD CONSTRAINT mission_pkey PRIMARY KEY (mission_id);


--
-- Name: node node_node_code_key; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.node
    ADD CONSTRAINT node_node_code_key UNIQUE (node_code);


--
-- Name: node node_pkey; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.node
    ADD CONSTRAINT node_pkey PRIMARY KEY (node_id);


--
-- Name: towing_car towing_car_code_key; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.towing_car
    ADD CONSTRAINT towing_car_code_key UNIQUE (code);


--
-- Name: towing_car towing_car_pkey; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.towing_car
    ADD CONSTRAINT towing_car_pkey PRIMARY KEY (towing_car_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_employee_code_key; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_employee_code_key UNIQUE (employee_code);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: idx_driving_log_car_time; Type: INDEX; Schema: public; Owner: A402
--

CREATE INDEX idx_driving_log_car_time ON public.driving_log USING btree (towing_car_id, created_at);


--
-- Name: idx_mission_log_mission_id; Type: INDEX; Schema: public; Owner: A402
--

CREATE INDEX idx_mission_log_mission_id ON public.mission_log USING btree (mission_id);


--
-- Name: flight fk56nmvny8si6peskxv0ifk6kw4; Type: FK CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.flight
    ADD CONSTRAINT fk56nmvny8si6peskxv0ifk6kw4 FOREIGN KEY (assigned_towing_car_id) REFERENCES public.towing_car(towing_car_id);


--
-- Name: towing_car fk5bmbikf6d1x044x705ckpcfw; Type: FK CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.towing_car
    ADD CONSTRAINT fk5bmbikf6d1x044x705ckpcfw FOREIGN KEY (last_node_id) REFERENCES public.node(node_id);


--
-- Name: mission fkf06kqfch0653yt0hl8ragmth7; Type: FK CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.mission
    ADD CONSTRAINT fkf06kqfch0653yt0hl8ragmth7 FOREIGN KEY (pilot_id) REFERENCES public.users(user_id);


--
-- Name: edge fkhad697ng5jci79p2st3w514yb; Type: FK CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.edge
    ADD CONSTRAINT fkhad697ng5jci79p2st3w514yb FOREIGN KEY (dst_node_id) REFERENCES public.node(node_id);


--
-- Name: mission fkjjhosixb6fk1ywa8wb2jqorg9; Type: FK CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.mission
    ADD CONSTRAINT fkjjhosixb6fk1ywa8wb2jqorg9 FOREIGN KEY (flight_schedule_id) REFERENCES public.flight(flight_schedule_id);


--
-- Name: flight fkmofq89ullrd4qk1hllnyf8pn5; Type: FK CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.flight
    ADD CONSTRAINT fkmofq89ullrd4qk1hllnyf8pn5 FOREIGN KEY (aircraft_id) REFERENCES public.aircraft(aircraft_id);


--
-- Name: mission fkp39uqn0qvlxlf8khxmi28epyo; Type: FK CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.mission
    ADD CONSTRAINT fkp39uqn0qvlxlf8khxmi28epyo FOREIGN KEY (towing_car_id) REFERENCES public.towing_car(towing_car_id);


--
-- Name: flight fkrurcr0dvv0c0ql9jqcvycf45r; Type: FK CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.flight
    ADD CONSTRAINT fkrurcr0dvv0c0ql9jqcvycf45r FOREIGN KEY (towing_car_id) REFERENCES public.towing_car(towing_car_id);


--
-- Name: flight fksjbllm8tcfi09wn05qpxp7yb9; Type: FK CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.flight
    ADD CONSTRAINT fksjbllm8tcfi09wn05qpxp7yb9 FOREIGN KEY (pilot_id) REFERENCES public.users(user_id);


--
-- Name: edge fksxl97mjpewswsls4eyw3wjyap; Type: FK CONSTRAINT; Schema: public; Owner: A402
--

ALTER TABLE ONLY public.edge
    ADD CONSTRAINT fksxl97mjpewswsls4eyw3wjyap FOREIGN KEY (src_node_id) REFERENCES public.node(node_id);


--
-- PostgreSQL database dump complete
--

\unrestrict c674bp78cH7DAA9sCdhKZcnWG6yxeclXPagiW9etD8kHKX89ATbIvGF038Y8BwY

