spring:
  config:
    activate:
      on-profile: local

  # [Local Dev] Mock MQTT to avoid conflicts with shared broker

  datasource:
    url: jdbc:h2:mem:ats_db;MODE=PostgreSQL # Postgres 모드로 실행 (호환성 UP)
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # 껐다 켜면 초기화 (개발용)
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console 접속 가능
  mqtt:
    broker:
      url: tcp://13.125.137.99:8183
logging:
  level:
    org.springframework.web: DEBUG
    com.project: DEBUG
    org.springframework.session: DEBUG
    org.springframework.security.web.session: DEBUG

jwt:
  secret: "c2lsdmVybGlnaHQtdGVzdC1zZWNyZXQtbmVvbi1sYXNlci1hdGMtY29udHJvbC1jZW50ZXItMTIzNDU2Nzg=" # Base64 encoded dummy key (at least 256 bits)
  expiration: 86400000 # 24hrs
app:
  mqtt:
    mock: false

springwolf:
  enabled: true
  docket:
    info:
      title: Autowing Car Async API
      version: 1.0.0
      description: 차량 관제 실시간 통신 API
    base-package: com.project
    servers:
      local:
        protocol: ws
        host: localhost:8080
        description: Local WebSocket Server
  use-fqn: false # 클래스명을 짧게 표시

