# --- application.yml (공통) ---
spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:Backend/autowing_car/.env[.properties]
  profiles:
    active: dev # 기본은 로컬 개발 모드

  mqtt:
    broker:
      url: ssl://${MQTT_HOST}:${MQTT_PORT}
      # url: tcp://localhost:1883
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

app:
  mqtt:
    mock: false
  map:
    locations:
      - classpath:maps/my_map.yaml
    # External path for Hot-fix (will be checked first in prod if provided via env)
    external-locations: ${MAP_LOCATIONS:}
